### ISSUE TITLE
npm support

### ISSUE THREAD

**Issue by Kepro** [sebastianha/angular-bootstrap-checkbox#15]
Hi, great can please add npm support? thanks!

**Comment by sebastianha** [comment]
Do you have an example or pull request for me? I have never done this before.

**Comment by Kepro** [comment]
maybe read here, http://www.mattpalmerlee.com/2013/04/23/create-your-first-node-module-and-publish-it-to-the-npm-registry/ also is like same to bower :)

**Comment by eranimo** [comment]
This would be nice

**Comment by sebastianha** [comment]
See latest release, let me know if this works.

**Comment by McGiogen** [comment]
I'm sorry but this doesn't worked for npm. The problem is that [someone](https://github.com/Catalant/angular-bootstrap-checkbox) has published a fork of this package with the same name before you and now npm links the name "angular-bootstrap-checkbox" to his repository (which is also outdated).
You can see the problem in [this page](https://www.npmjs.com/package/angular-bootstrap-checkbox): the github link on the right is not your repo and the version is wrong.

[This link about disputes on npm](https://docs.npmjs.com/misc/disputes) should help you to solve the problem.

If someone has the same problem it is temporary fixable by using this value in package.json:
```
 "angular-bootstrap-checkbox": "git://github.com/sebastianha/angular-bootstrap-checkbox.git#0.5.0"
```

**Comment by McGiogen** [comment]
Any news on this?

**Comment by sebastianha** [comment]
Hi,
I am very sorry for not answering for such a long time. I took the chance and just emailed the package owner of the fork if he would be so nice and would free the package name so I can publish the original code under the name "angular-bootstrap-checkbox".

I think this should solve your problem, right?

**Comment by eranimo** [comment]
I have transferred ownership of the package. Sorry everyone! 

Also, for future reference, you can install packages from github like this:
```json
"angular-bootstrap-checkbox": "sebastianha/angular-bootstrap-checkbox"
```

There's no need for the full git url if it's from Github. In fact, there's no need to publish at all if the repo has a package.json file (and even if it doesn't you can get around that too)

**Comment by sebastianha** [comment]
Thank you very much, I just published the package.

**Comment by McGiogen** [comment]
Thank you for the tip!
